spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: jimisun
    url: jdbc:mysql://127.0.0.1:3306/weixinshop?characterEncoding=utf-8&useSSL=false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: true
  jackson:
    default-property-inclusion: non_null
  thymeleaf:
    cache: true
    check-template-location: true
    servlet:
      content-type: text/html
    enabled: true
    encoding: utf-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html

server:
  servlet:
    context-path:
  port: 8080
